# Pytorch fundamentals


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'1.12.1'

## Introduction to Tensor

### Creating tesors

Pytorch tensors are created using `torch.tensor()` = htttps://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                        [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [17]:
MATRIX[0]
MATRIX[1]

tensor([ 9, 10])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [6, 7, 8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [24]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [38]:
TENSOR = torch.tensor([[[1,0,0], [0,1,0], [0,0,1]],[[2,0,0], [0,2,0], [0,0,2]],[[3, 0, 0], [0, 3, 0], [0, 0, 3]]])
TENSOR

tensor([[[1, 0, 0],
         [0, 1, 0],
         [0, 0, 1]],

        [[2, 0, 0],
         [0, 2, 0],
         [0, 0, 2]],

        [[3, 0, 0],
         [0, 3, 0],
         [0, 0, 3]]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neraul networks learns is that the start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random nubmers -> look at data -> update random numbers`

Thorch random tensors = https://pytorch.org/docs/stable/generated/torch.rand.html

In [41]:
# Create a random tensor of size (3, 4)
RANDOM_TENSOR = torch.rand(3, 4)
RANDOM_TENSOR

tensor([[0.7491, 0.0594, 0.5838, 0.3097],
        [0.7778, 0.4901, 0.3768, 0.0492],
        [0.4411, 0.5347, 0.8396, 0.7676]])

In [55]:
# Create a random tensor with similar shape to an image tensor
RANDOM_IMAGE_SIZE_TENSOR = torch.rand(size=(224, 224, 3)) # height, width, colour channels (RGB)
RANDOM_IMAGE_SIZE_TENSOR.shape, RANDOM_IMGAE_SIZE_TENSOR.ndim

(torch.Size([224, 224, 3]), 5)

In [49]:
RANDOM_SIZE_TENSOR = torch.rand(size =(1, 2, 3, 4, 5))
RANDOM_SIZE_TENSOR

tensor([[[[[0.1952, 0.9437, 0.1757, 0.6954, 0.5358],
           [0.1155, 0.2044, 0.6676, 0.3715, 0.1321],
           [0.1823, 0.4429, 0.4464, 0.1368, 0.4893],
           [0.2464, 0.9658, 0.6705, 0.4242, 0.2169]],

          [[0.2612, 0.7891, 0.0815, 0.4647, 0.2567],
           [0.7279, 0.8014, 0.8687, 0.6516, 0.3536],
           [0.5260, 0.2114, 0.8989, 0.1931, 0.5880],
           [0.8457, 0.6263, 0.8371, 0.3294, 0.0861]],

          [[0.4084, 0.5792, 0.3768, 0.1861, 0.1992],
           [0.0573, 0.7238, 0.5328, 0.2309, 0.7063],
           [0.2279, 0.2476, 0.5660, 0.9366, 0.0841],
           [0.4785, 0.3845, 0.1175, 0.4782, 0.6786]]],


         [[[0.5095, 0.9712, 0.9898, 0.9193, 0.5158],
           [0.0226, 0.1863, 0.0601, 0.1002, 0.3204],
           [0.9059, 0.8718, 0.8981, 0.0216, 0.8148],
           [0.1025, 0.5001, 0.3075, 0.2115, 0.6585]],

          [[0.0619, 0.0893, 0.7568, 0.1674, 0.4707],
           [0.3504, 0.3961, 0.7491, 0.3807, 0.4089],
           [0.2414, 0.6914, 0.3496, 

### Zeros and ones

In [68]:
# Create a tensor of all zeros
ZEROS = torch.zeros(size=(3, 4))
ZEROS

In [56]:
ZEROS * RANDOM_TENSOR

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [58]:
# Create a tensor of all ones
ONES = torch.ones(size=(3, 4))
ONES

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [60]:
ONES.dtype

torch.float32

In [61]:
RANDOM_TENSOR.dtype

torch.float32

### Create a range of tensors and tensors-like

In [67]:
# Use torch.arange() instead of torch.range()
ONE_TO_TEN = torch.arange(start=1, end=11, step=1)
ONE_TO_TEN

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
# Creating tensors like
TEN_ZOROS = torch.zeros_like(ONE_TO_TEN)
TEN_ZOROS

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learing:
1. Tensors are not of the right datatype
2. Tensors are not of the right shape
3. Tensors are not on the right device

In [103]:
# Float 32 tensor
FLOAT_32_TENSOR = torch.tensor([3.0, 6.0, 9.0], 
                                dtype=None,             # what datatype is the tensor (eq. float32, float16)
                                device="cpu",           # what device is your tensor on
                                requires_grad=False)    # whether or not to track gradients with these tensor operations 
FLOAT_32_TENSOR

tensor([3., 6., 9.])

In [86]:
FLOAT_32_TENSOR.dtype

torch.float32

In [90]:
FLOAT_16_TENSOR = FLOAT_32_TENSOR.type(torch.float16)
FLOAT_16_TENSOR

tensor([3., 6., 9.], dtype=torch.float16)

In [94]:
FLOAT_16_TENSOR * FLOAT_32_TENSOR, (FLOAT_16_TENSOR * FLOAT_32_TENSOR).dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [95]:
INT_32_TENSOR = torch.tensor([3, 6, 9], dtype=torch.int32)
INT_32_TENSOR

tensor([3, 6, 9], dtype=torch.int32)

In [97]:
FLOAT_32_TENSOR * INT_32_TENSOR, (FLOAT_32_TENSOR * INT_32_TENSOR).dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [99]:
FLOAT_16_TENSOR * INT_32_TENSOR, (FLOAT_16_TENSOR * INT_32_TENSOR).dtype

(tensor([ 9., 36., 81.], dtype=torch.float16), torch.float16)

### Getting tensor attributes

1. Tensors are not of the right datatype    -> to get datatype from a tensor, can use `tensor.dype`
2. Tensors are not of the right shape       -> to get shape from a tensor, can use `tensor.shape`
3. Tensors are not on the right device      -> to get device from a tensor, can use `tensor.device`

In [100]:
# Create tensor
SOME_TENSOR = torch.rand(3, 4)
SOME_TENSOR

tensor([[0.8071, 0.4415, 0.0963, 0.7135],
        [0.0101, 0.9076, 0.2829, 0.3621],
        [0.6002, 0.7603, 0.5712, 0.1362]])

In [101]:
# Find out details about some tensor
print(SOME_TENSOR)
print(f"Datatype of tensor: {SOME_TENSOR.dtype}")
print(f"Shape of tensor: {SOME_TENSOR.shape}")       # you can also use size() instead of shape
print(f"Device of tensor: {SOME_TENSOR.device}")

tensor([[0.8071, 0.4415, 0.0963, 0.7135],
        [0.0101, 0.9076, 0.2829, 0.3621],
        [0.6002, 0.7603, 0.5712, 0.1362]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Tensor operations

Tensor operations include:
* Addition
* Substraction
* Multiplication (elemnt-wise)
* Division
* Matrix multiplication

In [104]:
# Create a tensor and add 10 to it
TENSOR = torch.tensor([1, 2, 3])
TENSOR + 10

tensor([11, 12, 13])

In [105]:
# Multiply tensor by 10
TENSOR * 10

tensor([10, 20, 30])

In [106]:
# Subtract 10
TENSOR - 10

tensor([-9, -8, -7])

In [108]:
# Try out PyTorch in-built functions
torch.mul(TENSOR, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in nearal networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplicaction (dot product)

There are two main rules that performing matrix multipliction needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [111]:
# Element-wise multiplication
print(TENSOR, "*", TENSOR)
print(f"Equals: {TENSOR * TENSOR}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [112]:
# Matrix multiplication
torch.matmul(TENSOR, TENSOR)

tensor(14)

In [113]:
TENSOR

tensor([1, 2, 3])

In [115]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [130]:
BIG_TENSOR = torch.rand(1000)

In [131]:
%%time
value = 0
for i in range(len(BIG_TENSOR)):
    value += BIG_TENSOR[i] * BIG_TENSOR[i]
value

CPU times: user 22.9 ms, sys: 1.43 ms, total: 24.3 ms
Wall time: 23.4 ms


tensor(345.8117)

In [132]:
%%time
a = torch.matmul(BIG_TENSOR, BIG_TENSOR)
print(a)

tensor(345.8119)
CPU times: user 2.26 ms, sys: 720 µs, total: 2.98 ms
Wall time: 2.39 ms


### One of the most common errors made in deep learning: shape errors

In [137]:
# Shapes for matrix mutliplication
tensor_A = torch.Tensor(([1, 2],
                        [3, 4],
                        [5, 6]))
tensor_B = torch.Tensor(([7, 10],
                        [8, 11],
                        [9, 12]))
torch.mm(tensor_A, tensor_B)        # torch m.m is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [138]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

Tp fix our tensor shape issue, we can manipulate the shape of one of aur tensors using **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [144]:
tensor_B, tensor_B.shape

(tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 torch.Size([3, 2]))

In [145]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([2, 3]))

In [151]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


## Tensor aggregation, finding the min, max, mean, sum ect

In [154]:
# Create a tensor
X = torch.arange(0, 100, 10)
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [155]:
# Find the min
torch.min(X), X.min()

(tensor(0), tensor(0))

In [156]:
# Find the max
torch.max(X), X.max()

(tensor(90), tensor(90))

In [160]:
# Find mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(X.type(torch.float32)), X.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [161]:
# Find the sum
torch.sum(X), X.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [162]:
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [163]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
X.argmin()

tensor(0)

In [164]:
X[0]

tensor(0)

In [165]:
# Find the position in tensor that has the maximum value with argmax() -> returns index position of target tensor where the maximum value occurs
X.argmax()

tensor(9)

In [166]:
X[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a definded shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combining multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to target tensor
* Permute - return a view of the input with dimensions permuted (swapped in a certain way)

In [176]:
# Lets create a tensor
import torch
X = torch.arange(1., 10.)
X, X.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [202]:
# Add an extra dimension
X_reshaped = X.reshape(1, 9)
X_reshaped, X_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [178]:
# Change the view
Z = X.view(1, 9)
Z, Z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [180]:
# Changing Z changes X (because a vew of a tensor shares the same memory as the original tensor)
Z[:, 0] = 5
Z, X

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [191]:
# Stack tensors on top of each other
X_stacked = torch.stack([X, X, X, X], dim = 0)
X_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [195]:
print(f"torch.stack dim=0: \n{torch.stack([X, X, X, X], dim = 0)}")
print(f"torch.stack dim=1: \n{torch.stack([X, X, X, X], dim = 1)}")
print(f"torch.vstack: \n{torch.vstack([X, X, X, X])}")
print(f"torch.hstack: \n{torch.hstack([X, X, X, X])}")

torch.stack dim=0: 
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.stack dim=1: 
tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])
torch.vstack: 
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.hstack: 
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [205]:
# torch.squeeze() - removes all single dimensions from a tensor
print(f"Previous tensor: {X_reshaped}")
print(f"Previous shape: {X_reshaped.shape}")

# Remove extra dimensions from x_reshaped
X_squeezed = X_reshaped.squeeze()
print(f"\nNew tensor: {X_squeezed}")
print(f"New shape: {X_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [211]:
# torch.unsqueeze() - adds a single dimension to target tensor at a specific dim
print(f"Previous target: {X_squeezed}")
print(f"Previous shape: {X_squeezed.shape}")

# Add an extra dimension with unsqueeze
X_unsqueezed = X_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor with dim=0: {X_unsqueezed}")
print(f"New shape dim=0: {X_unsqueezed.shape}")

X_unsqueezed = X_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor with dim=1: {X_unsqueezed}")
print(f"New shape dim=1 : {X_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor with dim=0: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape dim=0: torch.Size([1, 9])

New tensor with dim=1: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape dim=1 : torch.Size([9, 1])


In [232]:
# torch.permute - rearrages the dimension of a specified order
X_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearange the axis (or dim) order
X_permuted = X_original.permute(2, 0, 1) # shifts axis 0->1, 1->2 and 2->0

print(f"Previous shape: {X_original.shape}")
print(f"New shape: {X_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [239]:
X_original[0, 0, 0] = 1234

X_original[0, 0, 0], X_permuted[0, 0, 0]

(tensor(1234.), tensor(1234.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [235]:
# Create a tensor
import torch
X = torch.arange(1, 10).reshape(1, 3, 3)
X, X.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [240]:
# Let's index on our new tensor
X[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [241]:
# Let's index on the middle bracket (dim=1)
X[0][0], X[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [248]:
# Let's index on the most inner bracket (last dimension)
X[0][2][2]

tensor(9)

In [249]:
# You can also use ":" to select "all" of a target dimension
X[:, 0]

tensor([[1, 2, 3]])

In [250]:
# Get all values of the 0th and 1st dimensions but only index 1 and 2nd dimension
X[:, :, 1]

tensor([[2, 5, 8]])

In [251]:
# Get all values of the 0 dimension but only the 1 index of the 1st and 2nd dimension
X[:, 1, 1]

tensor([5])

In [252]:
# Get index 0 of 0th and 1st dimension and all vlaues of 2nd dimension
X[0, 0, :]

tensor([1, 2, 3])

In [255]:
# Index on X to return 9
X[0, 2, 2]

tensor(9)

In [256]:
# Index on X to return 3, 6, 9
X[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing libary.

And because of this, Pytorch has functionality to interact with it.

* Data in NumPy to Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor to data in NumPy -> `torch.Tensor.numpy()`

In [264]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1., 8.)
tensor = torch.from_numpy(array) # when converting from numpy -> pytorch, pytorhc reflects numpy's default datatype of float64 unless specified otherwise (torch.type())
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [258]:
array.dtype

dtype('float64')

In [260]:
tensor.dtype

torch.float64

In [262]:
torch.arange(1., 8.).dtype

torch.float32

In [265]:
# Change the value of array what will this do to the tensor
array += 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [266]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [267]:
numpy_tensor.dtype

dtype('float32')

In [269]:
# Change the tensor, what happens to `numpy_tensor`?
tensor += 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a nearal network learns"

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> agian -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does in "flavour" the randomness.

In [271]:
torch.rand(3, 3)

tensor([[0.5959, 0.5003, 0.8708],
        [0.5343, 0.6952, 0.5860],
        [0.7263, 0.4485, 0.6782]])

In [272]:
# Create two random tensors
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1509, 0.2622, 0.5123, 0.3082],
        [0.1960, 0.8967, 0.8437, 0.4659],
        [0.5725, 0.9125, 0.2922, 0.8538]])
tensor([[0.1310, 0.9774, 0.4973, 0.9048],
        [0.8808, 0.6521, 0.5031, 0.3866],
        [0.8092, 0.2168, 0.3099, 0.0012]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [286]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra rescourses for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and Pytorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scienes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires an investment of purchasing a GPU, there's a lot of options (https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/)
3. Use cloud computing - GCP, AWS, Azure, these sevices allow you to rent computers on the cloud and access them

For 2, 3 Pythorch + GPU drivers (CUDA) takes a little bit of time to set up, to do this, refer to PyTorch setup documentations: https://pytorch.org/get-started/locally/ 

In [275]:
# Check for GPU accws with PyTorch
import torch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [278]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [279]:
# Count number of devices
torch.cuda.device_count()

0

## 2. Putting tensors (and models) on the GPU

The reason we want the tensors/model on the GPU is because using a GPU results in faster computations.

In [280]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [281]:
# Move tensore to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 3. Moving tensors back to the CPU

In [282]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [284]:
# To fix the GPU tensor with NumPy isue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_gpu

tensor([1, 2, 3])

## Exercise and Extra-curriculum

See exercises for this notebook here: https://www.leanrpytorch.io/00_pytorch_fundamentals/#exercises